### PR TITLE
Feature/ruby 187 support

### PR DESCRIPTION
**Pull request by ZeroPointEnergy**
Ruby 1.8.7 support.

This uses the 'posix-spawn' and 'uuid' library to get the functionality of Process.spawn and SecureRandom.uuid in ruby 1.8.7. There are also some other small fixes to make the plugin compatible to Ruby 1.8.7.

The gems are only required if you want to run the agent on 1.8.7 so it does not add dependencies for > 1.9.3 only users.

### CODE REVIEW

**Comment by richardc** [comment]
Sorry, but I just don't want this.  I appreciate the amount of effort you must have put in, but that's effort we were deliberately avoiding by not supporting a terribly old version of ruby.  Also adding external dependencies is something we prefer not to do with these plugins.

**Comment by ZeroPointEnergy** [comment]
I get that you rather not want to support old ruby versions. However there are still supported enterprise Linux versions which use ruby 1.8.7 as system ruby and will for a long time.

The patch is explicitly written in a way which will not introduce additional dependencies for people who are not using ruby 1.8.7.

**Comment by ZeroPointEnergy** [comment]
Will you accept the patch if I remove the gem dependencies (if that is possible)?

**Comment by richardc** [comment]
No, I don't want to support ruby 1.8.  It was a deliberate and conscious change to move away from it.  Any code you add/change to support it will be changes that we need to maintain going into the future, and I don't want to take on the maintenance cost.

**Pull request closed without merging**
